### ISSUE TITLE
Terraform crash with resource_alicloud_security_group.go

### ISSUE THREAD

**Issue by tmor** [aliyun/terraform-provider-alicloud#3442]
### Terraform Version

```
terraform -v
Terraform v0.13.6
+ provider registry.terraform.io/-/alicloud v1.121.1
+ provider registry.terraform.io/-/null v3.1.0
+ provider registry.terraform.io/hashicorp/alicloud v1.121.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

- resource_alicloud_security_group.go

### Terraform Configuration Files

```hcl
resource "alicloud_security_group" "system" {
  name        = "sg-****"
  description = "System created security group."
}

resource "alicloud_security_group" "datamanagement" {
  name        = "datamanagement-auto-created-security-group"
  description = "Data Management auto created security group. if deleted, Data Management will not work."
}

resource "alicloud_instance" "example" {
...
  security_groups = [
    alicloud_security_group.system.id,
    alicloud_security_group.datamanagement.id,
  ]
}
```

### Debug Output

I masked sensitive values to "****" .

<details>

<summary>logs of terraform plan</summary>

```shell
terraform plan
...
Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group.go:153:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_ecs.go:1340:
Describe ecs endpoint using region: "cn-hangzhou" got an error: &url.Error{Op:"Post", URL:"https://location-readonly.aliyuncs.com/?AccessKeyId=****&Action=DescribeEndpoints&Format=JSON&Id=cn-hangzhou&RegionId=cn-hangzhou&ServiceCode=ecs&Signature=****%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=****&SignatureType=&SignatureVersion=1.0&Timestamp=2021-04-14T08%3A13%3A52Z&Version=2015-06-12", Err:(*net.OpError)(0xc000f72190)}.



Error: rpc error: code = Unavailable desc = transport is closing



Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group.go:153:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_ecs.go:1340:
Describe ecs endpoint using region: "cn-hangzhou" got an error: &url.Error{Op:"Post", URL:"https://location-readonly.aliyuncs.com/?AccessKeyId=****&Action=DescribeEndpoints&Format=JSON&Id=cn-hangzhou&RegionId=cn-hangzhou&ServiceCode=ecs&Signature=ATIOodFYCMQapTbZGbi58hD8Vz0%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=148ec0bb046b2940bb2d1089c0e9e528&SignatureType=&SignatureVersion=1.0&Timestamp=2021-04-14T08%3A13%3A52Z&Version=2015-06-12", Err:(*net.OpError)(0xc000f727d0)}.



Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_ecs_auto_snapshot_policy.go:148:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_ecs.go:1659:
Describe ecs endpoint using region: "cn-hangzhou" got an error: &url.Error{Op:"Post", URL:"https://location-readonly.aliyuncs.com/?AccessKeyId=****&Action=DescribeEndpoints&Format=JSON&Id=cn-hangzhou&RegionId=cn-hangzhou&ServiceCode=ecs&Signature=kAfTSzoZg4eW4%2Fk9Y7MjJkvt%2B2I%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=75ab03da19fc247d9ed1a05e70f8745a&SignatureType=&SignatureVersion=1.0&Timestamp=2021-04-14T08%3A13%3A50Z&Version=2015-06-12", Err:(*net.OpError)(0xc000daeaf0)}.



Error: rpc error: code = Canceled desc = context canceled


panic: runtime error: invalid memory address or nil pointer dereference
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a2a46a]
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: goroutine 1250 [running]:
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: github.com/aliyun/terraform-provider-alicloud/alicloud.(*SlbService).DescribeSlbListener(0xc0006550e8, 0xc0014f40c0, 0x26, 0x60, 0x0, 0xc000e56d60)
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:       github.com/aliyun/terraform-provider-alicloud/alicloud/service_alicloud_slb.go:166 +0xca
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAliyunSlbListenerRead.func1(0x4daf45)
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:       github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_slb_listener.go:477 +0x88
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/resource/wait.go:22 +0x5b
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc000fa4d80, 0xc00039a4d0, 0xc000f34300, 0xc0016be120, 0xc0004a89f8, 0xc0004a89f0)
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/resource/state.go:103 +0x2a4
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1: created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
2021-04-14T17:13:53.683+0900 [DEBUG] plugin.terraform-provider-alicloud_v1.121.1:       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/resource/state.go:80 +0x1c5
2021-04-14T17:13:53.684+0900 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/alicloud/1.121.1/linux_amd64/terraform-provider-alicloud_v1.121.1 pid=22474 error="exit status 2"
...
```

</details>

### Panic Output

The crash.log has sensitive values and cannot be linked.

### Expected Behavior

Terraform works.

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

```shell
terraform init
terraform plan
```

### Important Factoids

- ecs on classic network. not VPC.
- These resources were created with terraform v0.12.
- I lowered a few versions of alicloud provider, but it did not solve the problem.

**Comment by xiaozhu36** [comment]
HI @tmor This issue probably comes from the network connection failed. Can you tell me where are you location when running terraform command?

**Comment by tmor** [comment]
> Can you tell me where are you location when running terraform command?

From Tokyo, Japan.
I have run terraform plan dozens of times for several days and the same error.
I don't think it is a network problem because it is reproducible.
