### ISSUE TITLE
terraform-provider-alicloud_v1.139.0 plugin crashed with alicloud_db_readonly_instance

### ISSUE THREAD

**Issue by tmor** [aliyun/terraform-provider-alicloud#4150]
### Terraform Version

```shell
terraform -v
Terraform v1.0.9 on linux_amd64
+ provider registry.terraform.io/aliyun/alicloud v1.139.0
+ provider registry.terraform.io/hashicorp/alicloud v1.139.0
```

### Affected Resource(s)

- alicloud_db_readonly_instance

### Terraform Configuration Files

```hcl
provider "alicloud" {
  profile = "example"
  region  = "cn-hangzhou"
}

resource "alicloud_db_readonly_instance" "example_replica" {
  count = 1
  master_db_instance_id = "rds****"
  engine_version        = "5.6"
  instance_type         = "rds.mysql.s2.large"
  instance_storage      = "50"
  instance_name         = "example-replica"
  vswitch_id            = "vsw-****"
}
```

### Panic Output

<details>

```shell
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵

Stack trace from the terraform-provider-alicloud_v1.139.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 19 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.buildDBReadonlyCreateRequest(0xc001b536c0, 0x6635060, 0xc00122a000, 0x0, 0xc000ddc408, 0x5704160)
        github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_db_readonly_instance.go:656 +0x151f
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudDBReadonlyInstanceCreate(0xc001b536c0, 0x6635060, 0xc00122a000, 0x2, 0xc3e13e0)
        github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_db_readonly_instance.go:208 +0xc7
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0009af080, 0xc001a2c6e0, 0xc001222540, 0x6635060, 0xc00122a000, 0x5704101, 0xc000ddc398, 0xc001224b70)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000f5a480, 0xc0011b5a18, 0xc001a2c6e0, 0xc001222540, 0xc001220748, 0xc0018601f0, 0x5706f20)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00014bc18, 0x6c49150, 0xc0012143c0, 0xc001a287e0, 0xc00014bc18, 0xc0012143c0, 0xc00120db80)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5f35ca0, 0xc00014bc18, 0x6c49150, 0xc0012143c0, 0xc001a28780, 0x0, 0x6c49150, 0xc0012143c0, 0xc001216700, 0x681)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000380f00, 0x6cb9338, 0xc000381680, 0xc00022cc00, 0xc000c14420, 0xc391420, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000380f00, 0x6cb9338, 0xc000381680, 0xc00022cc00, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd4c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001274b50, 0xc000380f00, 0x6cb9338, 0xc000381680, 0xc00022cc00)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-alicloud_v1.139.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

</details>

### Expected Behavior

rds readonly instance created.

### Actual Behavior

terraform-provider-alicloud_v1.139.0 plugin crashed

### Steps to Reproduce

1. `terraform init`
1. `terraform apply -target alicloud_db_readonly_instance.example_replica`

### Important Factoids

- Regin: cn-hangzhou
- In VPC

**Comment by xuzhang3** [comment]
This issue has been resolved and the feature/fix has been released. Closing as completed.

**Comment by xuzhang3** [comment]
"(This issue has been ...)"
