### ISSUE TITLE
Terraform-provider-alicloud_v1.159.0 plugin crashed! when doing terraform destroy

### ISSUE THREAD

**Issue by rkrezov2048** [aliyun/terraform-provider-alicloud#4674]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
terraform destroy on alicloud_kvstore_connection
```
alicloud_kvstore_connection.aspara_redis (deposed object 45c722b8): Refreshing state... [id=r-f2z8d1e66e6e0b84]
alicloud_vpc.redis_vpc: Refreshing state... [id=vpc-d7od0kvyeszehyql4191g]
alicloud_vswitch.vswredisa: Refreshing state... [id=vsw-d7oggdn3pyoa9hbala3x1]
alicloud_kvstore_instance.aspara-redis: Refreshing state... [id=r-f2z8d1e66e6e0b84]
alicloud_kvstore_connection.aspara_redis: Refreshing state... [id=r-f2z8d1e66e6e0b84]
alicloud_kvstore_connection.aspara_redis (deposed object 45c722b8): Refreshing state... [id=r-f2z8d1e66e6e0b84]
╷
│ Error: Plugin did not respond
│ 
│   with alicloud_kvstore_instance.aspara-redis,
│   on main.tf line 18, in resource "alicloud_kvstore_instance" "aspara-redis":
│   18: resource "alicloud_kvstore_instance" "aspara-redis" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with alicloud_kvstore_connection.aspara_redis,
│   on main.tf line 43, in resource "alicloud_kvstore_connection" "aspara_redis":
│   43: resource "alicloud_kvstore_connection" "aspara_redis" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-alicloud_v1.159.0 plugin:

panic: interface conversion: interface {} is nil, not *connectivity.AliyunClient

goroutine 16 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudKvstoreConnectionRead(0xc000fed6c0, 0x0, 0x0, 0xc000fed6c0, 0x0)
        github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_kvstore_connection.go:75 +0x558
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000fe7a00, 0xc00014d860, 0x0, 0x0, 0xc00000e3e8, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0005619d0, 0x7cadc10, 0xc0017fcd80, 0xc00014d540, 0xc0005619d0, 0xc0017fcd80, 0xc001c86b80)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x6f46620, 0xc0005619d0, 0x7cadc10, 0xc0017fcd80, 0xc0014c8900, 0x0, 0x7cadc10, 0xc0017fcd80, 0xc00125de40, 0x153)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005c2d80, 0x7d21cf8, 0xc0005c3500, 0xc001c17800, 0xc0006a5770, 0xd4d45d0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0005c2d80, 0x7d21cf8, 0xc0005c3500, 0xc001c17800, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd4c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0016c8830, 0xc0005c2d80, 0x7d21cf8, 0xc0005c3500, 0xc001c17800)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-alicloud_v1.159.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by rkrezov2048** [comment]
when issuing terraform destroy the provider crashed with this output.
