### ISSUE TITLE
terraform crashes in remote state

### ISSUE THREAD

**Issue by mcqj** [aliyun/terraform-provider-alicloud#5380]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.1.9

### Affected Resource(s)
- OSS remote state

### Terraform Configuration Files
```hcl
terraform {
  backend "oss" {
    region = "eu-west-1"
    bucket = "***************"
    key = "************"
    tablestore_table = "******"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
```
﻿!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x154
panic({0x2f2c560, 0x4d9ac50})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.(*TableStoreClient).doRequestWithRetry(0x0, {0x32c7318, 0x7}, {0x3828f20, 0xc000c2a2c0}, {0x3828f50, 0xc000ca3c20}, 0xc000ca3cb0)
	/Users/distiller/go/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/api.go:111 +0x7b
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.(*TableStoreClient).GetRow(0x3357230, 0xc000c5b648)
	/Users/distiller/go/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/api.go:643 +0x3fc
github.com/hashicorp/terraform/internal/backend/remote-state/oss.(*RemoteClient).getMD5(0xc0003a2fc0)
	/Users/distiller/project/project/internal/backend/remote-state/oss/client.go:227 +0x2c5
github.com/hashicorp/terraform/internal/backend/remote-state/oss.(*RemoteClient).Get(0x3807e60)
	/Users/distiller/project/project/internal/backend/remote-state/oss/client.go:73 +0xe7
github.com/hashicorp/terraform/internal/states/remote.(*State).refreshState(0xc000ca4000)
	/Users/distiller/project/project/internal/states/remote/state.go:111 +0x2e
github.com/hashicorp/terraform/internal/states/remote.(*State).RefreshState(0x0)
	/Users/distiller/project/project/internal/states/remote/state.go:104 +0x85
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000372ea0, {0xc00004e050, 0x0, 0x0})
	/Users/distiller/project/project/internal/command/init.go:294 +0x1598
github.com/mitchellh/cli.(*CLI).Run(0xc000124280)
	/Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
	/Users/distiller/project/project/main.go:309 +0x1509
main.main()
	/Users/distiller/project/project/main.go:58 +0x19
```

### Expected Behavior
Init of config

### Actual Behavior
Crash

**Comment by mcqj** [comment]
I've managed to get past the crash.
I had left `tablestore_endpoint` out of the backend config.
