### ISSUE TITLE
 Error: Plugin did not respond on terraform plan on  alicloud_cloud_storage_gateway_gateway

### ISSUE THREAD

**Issue by snps-ksh** [aliyun/terraform-provider-alicloud#6167]
Hi Team, We have made OSS cloud storage gateway from terraform on our Alicloud account. It was made and provisioned successfully, no configuration or file changes made and few days back we started seeing `│ Error: Plugin did not respond` on the cloud storage gateway resource.

We have tried multiple provider version and latest too, could find any mention of the resources in provider release after 1.196.0,
also we tried removing it's state and importing it, it shows it imported it successfully but on `terraform plan` it gives the same `│ Error: Plugin did not respond`

### Terraform Version : 
Terraform v1.3.3
on linux_amd64

### Affected Resource(s)
- alicloud_cloud_storage_gateway_gateway

 ### Terraform Alibaba Provider  version
We are facing issues  with alicloud below provider version and have faced the same issues/errors.
- alicloud 1.204.1
- alicloud 1.196.0
- alicloud 1.197.0

### Debug Output

> Error: Plugin did not respond
│ 
│   with module.kb_data_bucket.alicloud_cloud_storage_gateway_gateway.default[0],
│   on ../../../../../main.tf line 79, in resource "alicloud_cloud_storage_gateway_gateway" "default":
│   79: resource "alicloud_cloud_storage_gateway_gateway" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-alicloud_v1.204.1 plugin:
panic: interface conversion: interface {} is nil, not bool

> goroutine 138 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudCloudStorageGatewayGatewayRead(0xc001d0e230, {0x6afaa80?, 0xc000101800?})
       github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_cloud_storage_gateway_gateway.go:204 +0x4c5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00152d600, 0xc000646500, {0x6afaa80, 0xc000101800})
       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:455 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00012db68, {0xc002363ef0?, 0x526c06?}, 0xc002363ef0)
       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:525 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x64181a0?, 0xc00012db68}, {0x74b7bf0, 0xc00298cd80}, 0xc00081c840, 0x0)
       github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00034f180, {0x7501d18, 0xc000239680}, 0xc002470c60, 0xc001c7bd40, 0xd2f04f0, 0x0)
       google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00034f180, {0x7501d18, 0xc000239680}, 0xc002470c60, 0x0)
       google.golang.org/grpc@v1.40.0/server.go:1626 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
       google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
       google.golang.org/grpc@v1.40.0/server.go:939 +0x28a

> Error: The terraform-provider-alicloud_v1.204.1 plugin crashed!

>This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

>Operation failed: failed running terraform plan (exit 1)

### Expected Behavior
Terraform plan successful

### Actual Behavior
│ Error: Plugin did not respond

### Steps to Reproduce
`terraform plan`

**Comment by xuzhang3** [comment]
This issue has been resolved and the feature/fix has been released. Closing as completed.

**Comment by xuzhang3** [comment]
"(This issue has been ...)"
